### PR TITLE
Use dvc.yaml top-level plots

### PR DESCRIPTION
**Pull request by dberenbaum**
Basic configuration to use top-level plots without changing existing plots

### CODE REVIEW

**Comment by dberenbaum** [comment]
Note: I'm having trouble getting the plots to load on a fresh clone after `dvc pull` (they work fine from CLI and in my existing repo):

Screenshot 2022-11-15 at 3 54 43 PM

**Comment by shcheklein** [comment]
@dberenbaum while it's not lost, could you tar the folder and share it please?

**Comment by shcheklein** [comment]
I was able to reproduce the issue, I'll create a ticket or fix it.

**Comment by dberenbaum** [comment]
I don't think it's a performance issue. I can get plots to show up quickly if I toggle the options on the sidebars:

https://user-images.githubusercontent.com/2308172/202298433-7cdefe76-34dd-4c71-adba-41c1a3fcd219.mov


https://user-images.githubusercontent.com/2308172/202298567-7701f7d0-0882-48cd-a926-4d00a3881bca.mov

For some reason, the initial call is failing to render anything in VS Code. The same command renders plots and json in the cli, so hard for me to tell why it's hanging like this.

**Comment by shcheklein** [comment]
Yep, it's both. It was in my comment:

> But also there is something else, in this case even after DVC is done VS Code doesn't show those plots. I'm looking into this

**Comment by shcheklein** [comment]
>  Performance for me is very different:

You have them in cache? It clear that it's trying to fetch file by file for multiple commits from remote in a single thread. And it takes a quite long time.

**Comment by dberenbaum** [comment]
Even if I clone from scratch and open without doing any pull first, it takes longer but still only ~5 seconds:

```
[version: 0.5.12, 2022-11-16T21:42:18.288Z, pid: 30765] > /Users/dave/miniforge3/envs/dvc/bin/dvc plots diff 01e7f58 16a18b1 57f4589 workspace -o .dvc/tmp/plots --split --json - INITIALIZED
[version: 0.5.12, 2022-11-16T21:42:23.386Z, pid: 30765] > /Users/dave/miniforge3/envs/dvc/bin/dvc plots diff 01e7f58 16a18b1 57f4589 workspace -o .dvc/tmp/plots --split --json - COMPLETED (5099ms)
```

**Comment by shcheklein** [comment]
Do you use some global DVC cache by chance? What is the `dvc cache dir` in the project? 

It might be some difference in network 🤷

**Comment by dberenbaum** [comment]
I can get up to 7s but nothing approaching 40s:


https://user-images.githubusercontent.com/2308172/202302068-b0d7608b-a944-4f77-af8e-847a3fc67d8b.mov

**Comment by dberenbaum** [comment]
> Do you use some global DVC cache by chance? What is the `dvc cache dir` in the project?

```
$ dvc cache dir
/private/tmp/vscode-dvc-demo/.dvc/cache
```

My download speeds are <100Mbps. Maybe the data is stored in us-east and that makes a big difference?

**Comment by shcheklein** [comment]
@dberenbaum could you please confirm that you can load plots now?

**Comment by dberenbaum** [comment]
LGTM!

https://user-images.githubusercontent.com/2308172/202535865-689f6f13-6608-49e4-8210-fbc8b748ad24.mov

**Comment by shcheklein** [comment]
@dberenbaum perfect! now I need to figure out the performance issue on my end (and I think it's general for DVC) .... otherwise it's all not very usable.

**Comment by shcheklein** [comment]
@dberenbaum meanwhile we can merge this probably? any ideas about some other plots for this repo - bar charts, etc?

**Pull request merged**
